services:
  - type: web
    name: homelx-chat-app
    env: node
    buildCommand: |
      npm run install:all
      npm run build:frontend
    startCommand: npm start
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: NODE_VERSION
        value: 18.18.0
    healthCheckPath: /api/health
    autoDeploy: true
